export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";


export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_MODIFY_PROFILE_REQUEST = "USER_MODIFY_PROFILE_REQUEST";
export const USER_MODIFY_PROFILE_SUCCESS = "USER_MODIFY_PROFILE_SUCCESS";
export const USER_MODIFY_PROFILE_FAIL = "USER_MODIFY_PROFILE_FAIL";


