//for uploading the whole post to the website
export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST" 
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS" 
export const VIDEO_UPLOAD_FAIL = "VIDEO_UPLOAD_FAIL"

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST"
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS"  
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL"

export const LIKE_VIDEO_REQUEST = "LIKE_VIDEO_REQUEST"
export const LIKE_VIDEO_SUCCESS = "LIKE_VIDEO_SUCCESS"
export const LIKE_VIDEO_FAIL = "LIKE_VIDEO_FAIL"

export const CANCEL_LIKE_REQUEST = "CANCEL_LIKE_REQUEST"
export const CANCEL_LIKE_SUCCESS = "CANCEL_LIKE_SUCCESS" 
export const CANCEL_LIKE_FAIL = "CANCEL_LIKE_FAIL"

export const COMMENT_VIDEO_REQUEST = "COMMENT_VIDEO_REQUEST" 
export const COMMENT_VIDEO_SUCCESS = "COMMENT_VIDEO_SUCCESS" 
export const COMMENT_VIDEO_FAIL = "COMMENT_VIDEO_FAIL" 

export const SHARE_VIDEO_REQUEST = "SHARE_VIDEO_REQUEST"
export const SHARE_VIDEO_SUCCESS = "SHARE_VIDEO_SUCCESS"
export const SHARE_VIDEO_FAIL = "SHARE_VIDEO_FAIL"

export const VIEW_VIDEO_REQUEST = "VIEW_VIDEO_REQUEST"
export const VIEW_VIDEO_SUCCESS = "VIEW_VIDEO_SUCCESS"
export const VIEW_VIDEO_FAIL = "VIEW_VIDEO_FAIL"

//for uploading the video itself to the server 
export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL";

